### ISSUE TITLE
Excited to see an implementation of this

### ISSUE THREAD

**Issue by dhanush-ai1990** [nke001/sparse_attentive_backtracking_release#1]
I am really excited to see an implementation of this in Pytorch. Do you have an ETA for this ?

**Comment by nke001** [comment]
sorry for the delayed response. we planned to release the code earlier, but our lab is  physically moving at the moment, so the cluster  is down. We plan to release this within the first week of Jan when our cluster is back up running. Apologies for the inconvenience.

**Comment by duanyu** [comment]
Excited to see it, too :)

**Comment by nke001** [comment]
We are really sorry for the delay. We only released the code last week. But it is here. The code does use an earlier version of pytorch, but it's all the the yaml file :) You can create a conda env with the env.yaml file.
